# Generated by Django 4.1.3 on 2023-01-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_productinfo_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='num',
        ),
    ]
