# Generated by Django 4.1.3 on 2023-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_productinfo_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='ps',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
