# Generated by Django 4.1.3 on 2023-01-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_productinfo_ps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='ps',
            field=models.CharField(blank=True, default='NO ps', max_length=256, null=True),
        ),
    ]
