# Generated by Django 4.1.3 on 2023-01-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_productinfo_ps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='ps',
        ),
    ]
